# Generated by Django 2.1.4 on 2019-02-11 14:04

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_type', models.CharField(choices=[('Y', '年度预算'), ('M', '月度预算')], default='Y', max_length=2, verbose_name='预算类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('remark', models.CharField(blank=True, default=0, max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '预算',
                'verbose_name_plural': '预算',
                'ordering': ['user', 'budget_type'],
            },
        ),
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('attr', models.IntegerField(choices=[(0, '收入'), (1, '支出')], default=1, verbose_name='分类属性')),
                ('fast_code', models.CharField(default='', max_length=10, verbose_name='快速代码')),
                ('icon', models.ImageField(upload_to='image/%Y/%m', blank=True, verbose_name='图标')),
                ('ordering', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '一级分类',
                'verbose_name_plural': '一级分类',
                'ordering': ['-ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('attr', models.IntegerField(choices=[(0, '收入'), (1, '支出')], default=1, verbose_name='分类属性')),
                ('fast_code', models.CharField(default='', max_length=10, verbose_name='快速代码')),
                ('icon', models.ImageField(upload_to='image/%Y/%m', blank=True, verbose_name='图标')),
                ('ordering', models.IntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category1', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '二级分类',
                'verbose_name_plural': '二级分类',
                'ordering': ['-ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, verbose_name='配置项')),
                ('value', models.CharField(max_length=100, verbose_name='配置值')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '用户设置',
                'verbose_name_plural': '用户设置',
                'ordering': ['user', 'key'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('level', models.IntegerField(default=0, verbose_name='会员等级')),
                ('mobile', models.CharField(max_length=16, unique=True, verbose_name='手机')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='邮箱')),
                ('integral', models.IntegerField(default=0, verbose_name='积分')),
                ('keep_date', models.IntegerField(default=0, verbose_name='记账天数')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('last_date', models.DateTimeField(auto_now=True, verbose_name='最后登录时间')),
                ('token', models.CharField(default='', max_length=100, verbose_name='登录凭证')),
                ('icon', models.ImageField(upload_to='image/%Y/%m', blank=True, verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='WasteBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_date', models.DateTimeField(default='2019-02-11 22:04:46', verbose_name='记账日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category1', verbose_name='一级分类')),
                ('category2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category2', verbose_name='二级分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '流水',
                'verbose_name_plural': '流水',
                'ordering': ['-account_date', 'user'],
            },
        ),
        migrations.AddField(
            model_name='config',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='用户id'),
        ),
    ]
