# Generated by Django 2.1.4 on 2019-02-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190211_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastebook',
            name='account_date',
            field=models.DateTimeField(default='2019-02-11 23:21:12', verbose_name='记账日期'),
        ),
    ]
