# Generated by Django 2.1.4 on 2019-02-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190211_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon_height',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='user',
            name='icon_width',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, height_field='icon_height', upload_to='image/%Y/%m', verbose_name='头像', width_field='icon_width'),
        ),
        migrations.AlterField(
            model_name='wastebook',
            name='account_date',
            field=models.DateTimeField(default='2019-02-11 23:35:20', verbose_name='记账日期'),
        ),
    ]
