# Generated by Django 2.1.4 on 2019-02-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190211_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='category1',
            name='icon_height',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='category1',
            name='icon_width',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='category2',
            name='icon_height',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='category2',
            name='icon_width',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='category1',
            name='icon',
            field=models.ImageField(blank=True, height_field='icon_height', upload_to='image/%Y/%m', verbose_name='图标', width_field='icon_width'),
        ),
        migrations.AlterField(
            model_name='category2',
            name='icon',
            field=models.ImageField(blank=True, height_field='icon_height', upload_to='image/%Y/%m', verbose_name='图标', width_field='icon_width'),
        ),
        migrations.AlterField(
            model_name='wastebook',
            name='account_date',
            field=models.DateTimeField(default='2019-02-11 23:41:09', verbose_name='记账日期'),
        ),
    ]
