# Generated by Django 2.1.4 on 2019-02-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190211_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category1',
            name='fast_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='快速代码'),
        ),
        migrations.AlterField(
            model_name='category1',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='category2',
            name='fast_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='快速代码'),
        ),
        migrations.AlterField(
            model_name='category2',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='wastebook',
            name='account_date',
            field=models.DateTimeField(default='2019-02-11 23:50:48', verbose_name='记账日期'),
        ),
    ]
