# Generated by Django 2.1.4 on 2019-02-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190211_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category1',
            name='icon_height',
        ),
        migrations.RemoveField(
            model_name='category1',
            name='icon_width',
        ),
        migrations.RemoveField(
            model_name='category2',
            name='icon_height',
        ),
        migrations.RemoveField(
            model_name='category2',
            name='icon_width',
        ),
        migrations.RemoveField(
            model_name='user',
            name='icon_height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='icon_width',
        ),
        migrations.AlterField(
            model_name='category1',
            name='icon',
            field=models.ImageField(blank=True, upload_to='image/%Y/%m', verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='category2',
            name='icon',
            field=models.ImageField(blank=True, upload_to='image/%Y/%m', verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='wastebook',
            name='account_date',
            field=models.DateTimeField(default='2019-02-11 23:58:51', verbose_name='记账日期'),
        ),
    ]
