# Generated by Django 2.1.4 on 2019-02-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190211_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastebook',
            name='account_date',
            field=models.DateTimeField(default='2019-02-12 15:39:49', verbose_name='记账日期'),
        ),
    ]
