# Generated by Django 2.1.4 on 2019-02-12 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190212_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['budget_type'], 'verbose_name': '预算', 'verbose_name_plural': '预算'},
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['key'], 'verbose_name': '用户设置', 'verbose_name_plural': '用户设置'},
        ),
        migrations.AlterModelOptions(
            name='wastebook',
            options={'ordering': ['-account_date'], 'verbose_name': '流水', 'verbose_name_plural': '流水'},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
        migrations.RemoveField(
            model_name='config',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wastebook',
            name='user',
        ),
        migrations.AlterField(
            model_name='category2',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c2', to='api.Category1', verbose_name='上级分类'),
        ),
        migrations.AlterField(
            model_name='wastebook',
            name='account_date',
            field=models.DateTimeField(default='2019-02-12 22:23:29', verbose_name='记账日期'),
        ),
    ]
